spring.application.name=Pagos-service
spring.data.mongodb.uri=mongodb://admin:password@mongodb_microservicios:27017/product_db?authSource=admin
spring.kafka.bootstrap-servers=kafka:29092
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration