server:
  port: 8083  # cambia según el servicio (8080, 8081, 8082, etc.)

spring:
  application:
    name: pagos-service  # un nombre único para cada servicio

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true